GET localhost:8000/api/usuarioCaracteristicas
Accept: application/json


###
GET localhost:8000/api/ponentes
Accept: application/json

###
GET localhost:8000/api/ponentes/6
Accept: application/json

###
PUT localhost:8000/api/ponentes/5
Accept: application/json
Content-Type: application/json

{
    "nombre": "Cambio Put",
    "fotografia" : "67b1d9e55cf012.53497960.webp",
    "areas_experiencia": "C++",
    "redes_sociales": "https://www.instagram.com/"
}

###
GET localhost:8000/api/eventos
Accept: application/json

###
POST localhost:8000/api/eventos
Accept: application/json
Content-Type: application/json

{
    "nombre": "Taller de PHP",
    "descripcion": "programacion de jornadas estudiantiles",
    "ponente_id": 6,
    "tipo_evento": "Taller",
    "dia": "Viernes",
    "hora_inicio": "10:00",
    "cupo_maximo": 50,
    "cupo_actual": 0
}

###
POST localhost:8000/api/estudiantes
Accept: application/json
Content-Type: application/json

{
    "email": "alejandrocabrerabarea@gmail.com"
}

###
GET localhost:8000/api/estudiantes
Accept: application/json

###
PATCH localhost:8000/api/usuarioCaracteristicas/10
Accept: application/json
Content-Type: application/json

{
    "estudiante": false,
    "tipo_inscripcion": 2
}

###
POST localhost:8000/api/eventos
Accept: application/json
Content-Type: application/json

{
    "nombre": "afasdf",
    "descripcion": "fadfsd",
    "ponente_id": 1,
    "tipo_evento": "Taller",
    "dia": "Jueves",
    "hora_inicio": "10:00",
    "hora_fin": "10:55",
    "cupo_maximo": 50,
    "cupo_actual": []
}
