GET localhost:8000/api/usuarioCaracteristicas
Accept: application/json


###
GET localhost:8000/api/ponentes
Accept: application/json

###
DELETE localhost:8000/api/ponentes/4
Accept: application/json
